version: "3.8"
services:
  cacttusDb:
    image: postgres:13
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: spiness
      POSTGRES_USER: spiness
      POSTGRES_PASSWORD: spiness
      PGDATA: /var/lib/postgresql/data/spiness
    networks:
      - backend

networks:
  backend:
volumes:
  my-db: